import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/framefiftyone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            FrameFiftyOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homepage" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Homepage
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homepageone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomepageOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homepageseven" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomepageSeven
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homepageeight" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomepageEight
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/framefortynine" style={{ color: "#87CEFA", textDecoration: "none" }}>
            FrameFortyNine
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homepagefourteen" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomepageFourteen
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homepagefifteen" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomepageFifteen
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homepagesixteen" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomepageSixteen
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homepageseventeen" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomepageSeventeen
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homepageeighteen" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomepageEighteen
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homepagenineteen" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomepageNineteen
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homepagetwentythree" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomepageTwentyThree
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homepagetwentyfour" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomepageTwentyFour
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homepagetwentyfive" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomepageTwentyFive
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homepagetwentysix" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomepageTwentySix
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homepagetwentyseven" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomepageTwentySeven
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homepagetwentyeight" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomepageTwentyEight
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homepagetwentynine" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomepageTwentyNine
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homepagethirtythree" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomepageThirtyThree
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/framefiftytwo" style={{ color: "#87CEFA", textDecoration: "none" }}>
            FrameFiftyTwo
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/userprofile" style={{ color: "#87CEFA", textDecoration: "none" }}>
            UserProfile
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/userprofileone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            UserProfileOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/userprofilethree" style={{ color: "#87CEFA", textDecoration: "none" }}>
            UserProfileThree
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/userprofilefour" style={{ color: "#87CEFA", textDecoration: "none" }}>
            UserProfileFour
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/userprofilefive" style={{ color: "#87CEFA", textDecoration: "none" }}>
            UserProfileFive
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/framefifty" style={{ color: "#87CEFA", textDecoration: "none" }}>
            FrameFifty
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/admin" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Admin
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/adminone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AdminOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/framefiftythree" style={{ color: "#87CEFA", textDecoration: "none" }}>
            FrameFiftyThree
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/admintwo" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AdminTwo
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/adminthree" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AdminThree
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/adminfour" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AdminFour
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/adminfive" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AdminFive
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/admineight" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AdminEight
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/adminnine" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AdminNine
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/adminten" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AdminTen
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/framefiftyfour" style={{ color: "#87CEFA", textDecoration: "none" }}>
            FrameFiftyFour
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/admineleven" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AdminEleven
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/admintwelve" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AdminTwelve
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/adminthirteen" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AdminThirteen
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/adminfourteen" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AdminFourteen
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/adminfifteen" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AdminFifteen
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/adminsixteen" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AdminSixteen
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/adminseventeen" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AdminSeventeen
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/admineighteen" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AdminEighteen
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/adminnineteen" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AdminNineteen
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/framefiftyfive" style={{ color: "#87CEFA", textDecoration: "none" }}>
            FrameFiftyFive
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/admintwenty" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AdminTwenty
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/admintwentyone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AdminTwentyOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/admintwentytwo" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AdminTwentyTwo
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/admintwentythree" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AdminTwentyThree
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/admintwentyfour" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AdminTwentyFour
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/admintwentyfive" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AdminTwentyFive
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
