import { Text } from "./Text";
import { Heading } from "./Heading";
import { Img } from "./Img";
import { CheckBox } from "./CheckBox";
import { Button } from "./Button";
import { SelectBox } from "./SelectBox";
import { Input } from "./Input";
import { ReactTable } from "./ReactTable";
import { TextArea } from "./TextArea";
export { Text, Heading, Img, CheckBox, Button, SelectBox, Input, ReactTable, TextArea };
